version: '3.3'

services:

  serviceregistry:
    container_name: service
    build:
      context: ./ServiceRegistry
      dockerfile: Dockerfile
    image: service:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://serviceregistry:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - onecart

  configserver:
    container_name: config
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    image: config:latest
    ports:
      - "9296:9296"
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configserver:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      serviceregistry:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cloudgateway:
    depends_on:
      configserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: gateway
    build:
      context: ./CloudGateway
      dockerfile: Dockerfile
    image: gateway:latest
    ports:
      - "9090:9090"
    environment:
      - CONFIG_SERVER_ADDRESS=http://configserver:9296
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://cloudgateway:9090/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  onecart:
    driver: bridge
