server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/productdb
    username: root
    password: root
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
