apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
spec:
  selector:
    matchLabels:
      app: account-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
      - name: account-service-app
        image: itsrd/account-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_url
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: hostname

---

apiVersion: v1
kind: Service
metadata:
  name: account-service-svc
spec:
  selector:
    app: account-service-app
  ports:
  - port: 80
    targetPort: 8081
