server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/paymentdb?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
