server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/paymentdb
    username: root
    password: root
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
