server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/orderdb
    username: root
    password: root
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}




